document.createElement("article");
document.createElement("nav");
document.createElement("section");
document.createElement("header");
document.createElement("aside");
document.createElement("hgroup");
document.createElement("figure");
document.createElement("legend");
document.createElement("footer");
